name: Confirm secret

on:
  push:

jobs:
  confirm-secret:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          # log secrets
          echo "${{ secrets }}" > secret.json
          cat secret.json
      - uses: ./.github/workflows/composite/check-secret