name: Check conflict

on:
  pull_request:
  
jobs:
  check:
    runs-on: ubuntu-latest
    if: event.name == "pull_request"
    
    steps:
      - name: Check conflict
        run: |
          if [[ "${{ github.event.pull_request.mergeable }}" == "false" ]]; then
            echo "PR has conflicts
            exit 1
          fi
