name: Create PR

on:
  push:
    branches:
      - my-best-feature

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create branch
        run: |
          git checkout -b merge-my-best-feature
          git push -u origin merge-my-best-feature --force
      - name: Create Pull Request
        uses: scorebet/pull-request@v2
        with:
          source_branch: "merge-my-best-feature"                     # If blank, default: triggered branch
          destination_branch: "develop"          # If blank, default: master
          pr_title: "Pull ${{ github.ref }} into develop"
          pr_body: ":crown: *An automated PR to keep develop up to date*"  # Full markdown support, requires pr_title to be set
          pr_label: "merge"
          github_token: ${{ secrets.GITHUB_TOKEN }}
