# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        env:
          PULL_REQUEST: ${{ github.event.number }}
        run: |
          echo Hello, world!
          echo "PUll $PULL_REQUEST"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo ${{ github.event.number }}
          echo ${{ github.event.pull_request }}
          
      - name: Run ruby
        run: |
          pull_request=${{ github.event.pull_request }}
          postCommentResult=$(ruby -e '
            require "json"
            require "rubygems"
            require "faraday"

            puts '$pull_request'
          ')
          echo $postCommentResult
          
          
