name: Create merge branch and PR

on: 
  push:
    branches: 
      - release-candidate

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: switch to release-candidate
        run: git checkout release-candidate

      - name: checkout merge-release-candidate
        run: git checkout -b merge-release-candidate
      
      - name: merge release-candidate to merge-release-candidate
        run: git merge release-candidate

      - name: push changes from merge-release-candidate
        run: git push -u origin merge-release-candidate --force

  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "merge-release-candidate"                     # If blank, default: triggered branch
        destination_branch: "develop"          # If blank, default: master
        pr_title: "Pull ${{ github.ref }} into develop"
        pr_body: ":crown: *An automated PR*"  # Full markdown support, requires pr_title to be set
        github_token: ${{ secrets.GITHUB_TOKEN }}
