name: Multiline output

on:
  push:
  
jobs:
  test-multiline:
    runs-on: ubuntu-latest
    
    steps:
      - name: create string
        run: |
          MY_STRING=$(cat << EOF
          first line
          second line
          third line
          EOF
          )
          MY_STRING="${MY_STRING//'%'/'%25'}"
          MY_STRING="${MY_STRING//$'\n'/'%0A'}"
          MY_STRING="${MY_STRING//$'\r'/'%0D'}"
          
          echo "escaped string $MY_STRING"
          echo "::set-output name=content::$MY_STRING"
        id: my_string
      - name: display string
        run: |
          echo "The string is: ${{ steps.my_string.outputs.content }}"
      - name: js output
        id: js_step
        uses: actions/github-script@v6
        with:
          script: |
            core.setOutput('test', 'This is a\nmultiline string\nwith %age output');
      - name: display js string
        run: |
          echo "The string is: ${{ steps.js_step.outputs.test }}"
