name: Test version

on: 
  push:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # only using major version tag hoping we will get the minor and patch automatically
      - uses: tahirmt/test-github-action-version-checker@v1
